# Generated by Django 4.2.7 on 2025-07-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='body_language_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='communication_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='confidence_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='emotion_analysis_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='eye_contact_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='posture_analysis_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='speaking_pace_score',
            field=models.IntegerField(default=0),
        ),
    ]
